/*
* SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 
*/

/**
 * API MONPNRRBE
 * Componente API  MONPNRRBE del prodotto MONPNRR
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ChecklistProgettoRilevazione {
  rilevazione_domanda_id?: number;
  nome: string;
  note?: string;
  esito?: string;
  note_asr?: string;

  ultima_modifica: UltimaModifica | null;
  esito_verifica_liv2: boolean | null;
  nota_verifica_liv2: string | null;
  ultima_verifica_liv2: UltimaModifica | null;
  verificato_liv2: boolean | null;

  esito_verifica_liv3: boolean | null;
  nota_verifica_liv3: string | null;
  ultima_verifica_liv3: UltimaModifica | null;
  verificato_liv3: boolean | null;
}

export interface UltimaModifica {
  utente: string | null;
  data: string | null;
}
