/*
* SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 
*/

/**
 * API MONPNRRBE
 * Componente API  MONPNRRBE del prodotto MONPNRR
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ProceduraCig {
    descrizione_procedura_cig?: string;
    progressivo?: number;
    numero_cig?: string;
}
