/*
* SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 
*/

/**
 * API MONPNRRBE
 * Componente API  MONPNRRBE del prodotto MONPNRR
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Azienda } from "./azienda";
import { RupEntity, UltimaModifica, UltimaVerifica } from "./Progetti";

export interface ProgettoDettaglio { 
    checklist?: string;
    azienda?: Azienda;
    intervento?: string;
    cup?: string;
    rup?: RupEntity;
    ultima_modifica: UltimaModifica;
    ultima_verifica: UltimaVerifica;
    ultima_verifica_liv2: UltimaVerifica;
    ultima_verifica_liv3: UltimaVerifica;
    modalita_attuativa?: string;
}