application:
  title: monpnrr/monpnrrbe
  version: 1.1.0

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health
          - metrics
      base-path: /actuator
  server:
    port: 9000
server:  
  servlet:
    context-path: /monpnrrbe